language: cpp
compiler: gcc
dist: trusty
matrix:
  include:
    - env: JOB=1
    - env: JOB=2

before_install:
- openssl aes-256-cbc -K $encrypted_70a180dc4570_key -iv $encrypted_70a180dc4570_iv
  -in tra.enc -out tra -d
script:
- sudo ./bash.sh $JOB
